spring.application.name=examgo
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=testdb
spring.security.user.name=user
spring.security.user.password=user
jwt.secret=your-very-long-and-secure-secret-key-1234567890!@#$%^&*()
spring.mail.host=smtp.gmail.com
spring.mail.port=587

