spring.application.name=examgo
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=testdb
spring.security.user.name=user
spring.security.user.password=user
jwt.secret=your-very-long-and-secure-secret-key-1234567890!@#$%^&*()
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=imshashank72@gmail.com
spring.mail.password=cvkp utab jfdf unev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
